import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState} from 'react';
// import MultipleSelect from '@bit/lubuskie.material-ui.multiple-select-chips';
// import MultipleSelect from 'material-ui-multiple-select'

export default function Home() {
  	const [value, setValue] = useState([])
	const [error, setError] = useState("")
	const options = [{label: "First", value: 1}, {label: "Second", value: 2}, {label: "Third", value: 3}]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/SHAREROUTINE_LOGO.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span className={styles.title__shareroutine}>ShareRoutine</span>
          !</h1>
          <div className={styles.all_category}>
            <div className={styles.all_category1}>
            <div className={styles.all_category_1}>기획·마케팅·실무</div>
            <div className={styles.all_category_2}>디자인·영상</div>
            <div className={styles.all_category_3}>데이터·개발</div>
            <div className={styles.all_category_4}>외국어</div>
            <div className={styles.all_category_5}>재테크·투잡</div>
            </div>
            <div className={styles.all_category2}>
            <div className={styles.all_category_6}>댄스·뮤직</div>
            <div className={styles.all_category_7}>피트니스·스포츠</div>
            <div className={styles.all_category_8}>뷰티·마인드·펫</div>
            <div className={styles.all_category_9}>드로잉·사진·글</div>
            <div className={styles.all_category_10}>요리·공예·취미</div>
            </div>
        </div>
        <p className={styles.description}>
         ShareRoutine을 자세히 알고 싶다면?
        </p>
{/* multi select 임시 */}
        <div>
          {/* 참고 : https://bit.cloud/lubuskie/material-ui/multiple-select-chips/~dependencies */}
          	{/* <MultipleSelect
		label="Label"
		value={value}
		setValue={setValue}
		options={options}
		error={error}
		setError={setError}
	/> */}
</div>
{/*  */}
        <div className={styles.div}>
          <form
            className={styles.form}
              action="https://formspree.io/f/mbjwaodq"
              method="post"
            >
            <input className={styles.input}
              placeholder="이메일을 입력하시면, 루틴일정을 공유드려요 🌹"
                name="Email"
                id="email"
                // type="email"
            >
          </input>
           <button className={styles.btn} type="submit" >보내기</button>
           </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="./styleguide">
        Powered by <span className={styles.footer__name}>IseulPark</span>
          {/* <span className={styles.logo}>
            <Image src="/SHAREROUTINE_LOGO.png" alt="Logo" width={72} height={16} />
          </span> */}
          </a>
      </footer>
    </div>
  )
}
